Bump dependencies
auth0/auth0-spring-security-api pull request #4
Opened 2018-10-28 18:45 UTC by napstr

2018-10-29 17:17 UTC, lbalmaceda commented
I forgot to update this one on the past week.. This is good. But please, go and rollback the changes on `spring` and `servlet` dependencies since you are now using different majors and I can't know for sure what's the impact for this SDK's users.

2018-10-29 17:23 UTC, lbalmaceda requested changes
Added a comment above this review. Added suggested changes to avoid changing a dependency version to a new major.

2018-10-29 17:23 UTC, lbalmaceda commented on lib/build.gradle
> +    implementation 'org.springframework.security:spring-security-core:5.1.1.RELEASE'
```suggestion
    implementation 'org.springframework.security:spring-security-core:4.2.9.RELEASE'
```

2018-10-29 17:23 UTC, lbalmaceda commented on lib/build.gradle
> +    implementation 'org.springframework.security:spring-security-web:5.1.1.RELEASE'
```suggestion
    implementation 'org.springframework.security:spring-security-web:4.2.9.RELEASE'
```

2018-10-29 17:23 UTC, lbalmaceda commented on lib/build.gradle
> +    implementation 'org.springframework.security:spring-security-config:5.1.1.RELEASE'
```suggestion
    implementation 'org.springframework.security:spring-security-config:4.2.9.RELEASE'
```

2018-10-29 17:23 UTC, lbalmaceda commented on lib/build.gradle
> +    testCompile 'javax.servlet:javax.servlet-api:4.0.1'
```suggestion
    testCompile 'javax.servlet:servlet-api:2.5'
```

2018-10-29 17:23 UTC, lbalmaceda commented on lib/build.gradle
> +    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
```suggestion
    compileOnly 'javax.servlet:servlet-api:2.5'
```

2018-10-29 21:17 UTC, napstr commented
Gotcha, updated.

2018-10-29 21:20 UTC, lbalmaceda commented on build.gradle
> +wrapper {
I've never needed this before. Can you safely remove it? How have you updated the gradle version? I normally run `./gradlew wrapper  --gradle-version 4.10.2 --distribution-type all`

2018-11-22 16:34 UTC, lbalmaceda approved these changes

2018-11-22 16:35 UTC, merged