Add WWW-Authenticate header for 401 and 403 requests
auth0/auth0-spring-security-api pull request #51
Opened 2020-06-05 21:03 UTC by jimmyjames

### Changes

As raised in #47, the `WWW-Authenticate` headers should be sent on the response when the request is rejected due to a missing or invalid access token. This is specified by [RFC 6750](https://tools.ietf.org/html/rfc6750#section-3).

#### Scenarios

- Requests to a resource that require authorization that are rejected with a `401` due to an invalid or missing access token will have a `WWW-Authenticate` header included on the response.
- Requests to a resource that are rejected with a `403` due to insufficient scopes will have a `WWW-Authenticate` header included on the response.  

#### WWW-Authenticate header value

[RFC 6750](https://tools.ietf.org/html/rfc6750#section-3) does not require any specific attributes of the `WWW-Authenticate` header to be set. This PR simply includes an `error` attribute, with the following values:

- "Invalid token" for a `401` resulting from a missing or invalid access token
- "Insufficient scope" for a `403` resulting from a token with insufficient scopes

A couple notes on what could be added in the future, but is not included here as this change is focused on complying with RFC 6750 and enables future changes to the header attributes:

- In the case of `401` errors, we could unwrap the `AuthenticationException` and use the underlying exception cause to return a more specific `error` (e.g., invalid signature, expired token, etc).
- In the case of `403` errors, we _might_ be able to included the required scopes for the resource, as [was added to express-jwt-authz](https://github.com/auth0/express-jwt-authz/pull/20). That would require some more thought, since we'd need to be able to hook into the required scopes as configured by the application developer.
- We could include attributes such as the `realm` or `authorization_uri`, if those prove to be useful for callers.

Again, those possible additions are not included in this PR for the purposes of simplicity and compliance, but we can consider them going forward.

### References

- [RFC 6750](https://tools.ietf.org/html/rfc6750#section-3)
- #50 
- #47 

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

- [X] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [X] All existing and new tests complete without errors

2020-06-05 21:04 UTC, jimmyjames commented on lib/src/main/java/com/auth0/spring/security/api/JwtAccessDeniedHandler.java
> +    public void handle(HttpServletRequest request, HttpServletResponse response, AccessDeniedException accessDeniedException) throws IOException, ServletException {
`AccessDeniedHandler` specifies that `handle` must be public, which is why the class as package-private but the method as public

2020-06-09 15:19 UTC, jimmyjames commented
Codecov checks failing because of the lack of coverage around the `configure()` method of `JwtWebSecurityConfigurer`. There's not a great way to test this, as `HttpSecurity` is final (can't be mocked) and would probably require a spring integration test, which would require some type of controller under test.

2020-06-09 15:30 UTC, lbalmaceda requested changes

2020-06-09 15:30 UTC, lbalmaceda commented on lib/src/test/java/com/auth0/spring/security/api/JwtAccessDeniedHandlerTest.java
> +        AccessDeniedException exception = new AccessDeniedException("Forbidden");// mock(AccessDeniedException.class);
I seems this comment shouldn't be here?

2020-06-09 16:27 UTC, jimmyjames commented on lib/src/test/java/com/auth0/spring/security/api/JwtAccessDeniedHandlerTest.java
> +        AccessDeniedException exception = new AccessDeniedException("Forbidden");// mock(AccessDeniedException.class);
Fixed 👍

2020-06-09 18:08 UTC, lbalmaceda approved these changes

2020-06-09 18:09 UTC, merged